name=input('what is your name: ')
gender=input('are you a boy or a girl: ')
hometown=input('where do you come from: ')
father_name=input("what is your father's name: ")
mother_name=input("what is your mother's name: ")
age=input('what is your age: ')
favourite_sport=input('what is your favourite sport: ')
favourite_food=input('what is your favourite food: ')
print("                                                    ")
print(name + ' is a ' + gender + '.He comes from ' + hometown)
print(".His father's name is " + father_name + " .His mother's name is " + mother_name)
print('.He is ' + age + ' .He likes ' + favourite_food + ' and ' + favourite_sport)